### ISSUE TITLE
⚠️ EDGE CASE! If you facing wrong problem, you might need this.

### ISSUE THREAD

**Issue by evillt** [evillt/macmineable-release#10]
Since macMineable is still in early development. It may have some bugs we didn't fix or we don't know how to fix it.

So we write down this wiki to help you do some remedies.

**Comment by evillt** [comment]
## Keep mining even with App close and stoped

#9 

> For more than 10 minutes

### Do kill the mining process

Run the `monitor.app`

![image](https://user-images.githubusercontent.com/19513289/128296532-93c4bd1b-b150-45b7-a49e-862ac3089640.png)

Find the process name `xmrig`, then kill it.

![image](https://user-images.githubusercontent.com/19513289/128296797-e35f8670-a0e3-47f5-8c2b-acd901b917cd.png)

**Comment by kyfike** [comment]
Why is my SHIBA cypto balance 0 after I've been mining for over 15min?
![22A4C03F-7CEC-4CA4-8568-F7555246061E](https://user-images.githubusercontent.com/88905898/135539201-c24fb57d-df22-426a-ac1c-1daf9309bccd.jpeg)
[]

**Comment by kyfike** [comment]
Does this mine using the graphics card or CPU?

**Comment by evillt** [comment]
> Does this mine using the graphics card or CPU?

@kyfike supports CPU only for now.
