### ISSUE TITLE
control CPU usage

### ISSUE THREAD

**Issue by kilianso** [evillt/macmineable-release#2]
Hey there! Nice one, really like this port of unminable.

My mac mini is having a hard time mining Doge. How would you limit the CPU usage? I saw that there is a CLI command but that doesn't seem to have any effect using your tool. Any hint? And do you plan to integrate it as an option in the UI?

Keep it up 🙌

**Comment by evillt** [comment]
Thank you.

Current use `50%` of CPU for mining.

Planning to add a setting page for misc sets.

I'll release a new version in few days.

**Comment by evillt** [comment]
https://xmrig.com/docs/miner/config/cpu#max-threads-hint

And should according above.

**Comment by evillt** [comment]
Now support adjust CPU usage in https://github.com/evillt/macmineable-release/releases/tag/v0.6.0

**Comment by Starry-Night-pEaCe** [comment]
Hey Anthony,  

Nice app. Glad that you wrote it. I'd like to provide you with some feedback while running it.  

I was running version .6.0 on a older iMac. late 2015 with upgrade SSD. However, I encountered error messages like below, and the app would quit responding, until it gets restarted. Maybe it will provide you with  some hints for future version development?  Thanks appreciate your work.

=================================

Uncaught Exception:
TypeError: Object has been destroyed
at Socket.<anonymous> (/private/var/folders/nr/55nsp1n50cnbktyd0gyjbb8w0000gn/T/AppTranslocation/8B2818CC-AE91-475B-A362-CC9741417616/d/macMineable.app/Contents/Resources/app.asar/app/main.js:52:13)
at Socket.emit (events.js:327:22)
at addChunk (internal/streams/readable.js:309:12)
at readableAddChunk (internal/streams/readable.js:280:11)
at Socket.Readable.push (internal/streams/readable.js:223:10)
at Pipe.onStreamRead (internal/stream_base_commons.js:188:23

=========================================


Cheers.
