### ISSUE TITLE
UI renderer with no response, and become blank.

### ISSUE THREAD

**Issue by evillt** [evillt/macmineable-release#3]
Hey Anthony,  

Nice app. Glad that you wrote it. I'd like to provide you with some feedback running it.  

I was running version .6.0 on an older iMac. late 2015 with upgrade SSD. However, I encountered error messages like below, and the app would no respond, until it got restarted. Maybe it will provide you with  some hints for future version development?  Thanks appreciate your work.

```bash
Uncaught Exception:
TypeError: Object has been destroyed
at Socket.<anonymous> (/private/var/folders/nr/55nsp1n50cnbktyd0gyjbb8w0000gn/T/AppTranslocation/8B2818CC-AE91-475B-A362-CC9741417616/d/macMineable.app/Contents/Resources/app.asar/app/main.js:52:13)
at Socket.emit (events.js:327:22)
at addChunk (internal/streams/readable.js:309:12)
at readableAddChunk (internal/streams/readable.js:280:11)
at Socket.Readable.push (internal/streams/readable.js:223:10)
at Pipe.onStreamRead (internal/stream_base_commons.js:188:23
```

Cheers.

_Originally posted by @Starry-Night-pEaCe in https://github.com/evillt/macmineable-release/issues/2#issuecomment-870072937_

**Comment by evillt** [comment]
Running normally when you restarted? @Starry-Night-pEaCe

**Comment by Starry-Night-pEaCe** [comment]
yeah, it will be good for most of the day. Then Eventually, it becomes unresponsive, until another relaunch. I'm under macOS Big Sur V11.4

**Comment by evillt** [comment]
I'll try to debug, maybe it's hard to. Also, I'm under macOS BigSur 11.4 but never happened.

**Comment by Starry-Night-pEaCe** [comment]
yeah, appreciate your efforts.    It kinda freezes, I can drag the app, however, the interface is white blank, no display of hash rate or total coin collected.  here is another error message:

=========================
Uncaught Exception:
TypeError: Object has been destroyed
at Socket.<anonymous> (/private/var/folders/nr/55nsp1n50cnbktyd0gyjbb8w0000gn/T/AppTranslocation/5998253E-7DAA-4898-A974-C14D982A217F/d/macMineable.app/Contents/Resources/app.asar/app/main.js:52:13)
at Socket.emit (events.js:327:22)
at addChunk (internal/streams/readable.js:309:12)
at readableAddChunk (internal/streams/readable.js:280:11)
at Socket.Readable.push (internal/streams/readable.js:223:10)
at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

======================

**Comment by evillt** [comment]
I faced this problem before by running macMineable for more than 24 hours. Maybe you can try to reduce CPU usage on the setting page. I think is the UI process was killed.

> yeah, appreciate your efforts. It kinda freezes, I can drag the app, however, the interface is white blank, no display of hash rate or total coin collected. here is another error message:

**Comment by evillt** [comment]
From another user with the same issue.

> Hi Anthony,
One glitch I’ve noticed is that the progress window blanks to white. It still seems to be running but to get it back I quit then restart.
This happens after several hours each time.
Perhaps its a java issue?
Happy week!
Dennis

**Comment by Starry-Night-pEaCe** [comment]
Good Day Anthony,

The same computer restarted a couple of time in the last 24 hour with the following error report. not sure if it's related.  was running version .6.0. gonna download .7.0 and give it a try.

============================================

panic(cpu 2 caller 0xffffff801e154b46): "vm_pageout: no victim"@/System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.121.3/osfmk/vm/vm_pageout.c:3137
Backtrace (CPU 2), Frame : Return Address
0xffffffb08a88bbb0 : 0xffffff801e08e0dd 
0xffffffb08a88bc00 : 0xffffff801e1d4f33 
0xffffffb08a88bc40 : 0xffffff801e1c552a 
0xffffffb08a88bc90 : 0xffffff801e032a2f 
0xffffffb08a88bcb0 : 0xffffff801e08d8fd 
0xffffffb08a88bdd0 : 0xffffff801e08dbf3 
0xffffffb08a88be40 : 0xffffff801e89d81a 
0xffffffb08a88beb0 : 0xffffff801e154b46 
0xffffffb08a88bf70 : 0xffffff801e15524b 
0xffffffb08a88bfa0 : 0xffffff801e03213e 

Process name corresponding to current thread: kernel_task

Mac OS version:
20F71

Kernel version:
Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
Kernel UUID: 52A1E876-863E-38E3-AC80-09BBAB13B752
KernelCache slide: 0x000000001de00000
KernelCache base:  0xffffff801e000000
Kernel slide:      0x000000001de10000
Kernel text base:  0xffffff801e010000
__HIB  text base: 0xffffff801df00000
System model name: iMac16,2 (Mac-FFE5EF870D7BA81A)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 37557955064197
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00002228a491f43c
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000b930d4689 0x0000000000000000
last started kext at 121738996437: @filesystems.smbfs	3.6 (addr 0xffffff7fb993a000, size 487424)
last stopped kext at 191256957416: >!AFIVRDriver	4.1.0 (addr 0xffffff7fb764b000, size 8192)
loaded kexts:
@filesystems.smbfs	3.6
>!ATopCaseHIDEventDriver	4050.1
>AudioAUUC	1.70
@filesystems.autofs	3.0
>AGPM	122.1
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
@fileutil	20.036.15
>!AGraphicsDevicePolicy	6.3.3
>!AUpstreamUserClient	3.6.8
@AGDCPluginDisplayMetrics	6.3.3
>pmtelemetry	1
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
>!AHDA	283.15
|IO!BSerialManager	8.0.5d7
@Dont_Steal_Mac_OS_X	7.0.0
>!AHV	1
>!ADiskImages2	1
>!A!IBDWGraphics	16.0.4
>!AMCCSControl	1.14
>!AThunderboltIP	4.0.3
>!A!IBDWGraphicsFramebuffer	16.0.4
|Broadcom!B20703USBTransport	8.0.5d7
>eficheck	1
>!ASMCLMU	212
>!ALPC	3.1
>!A!ISlowAdaptiveClocking	4.0.0
|IO!BUSBDFU	8.0.5d7
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.100.11
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@filesystems.apfs	1677.120.9
>AirPort.BrcmNIC	1400.1.1
>!ASDXC	1.9.0
|!ABCM5701Ethernet	11.0.0
>!AAHCIPort	346.100.2
@private.KextAudit	1.0
>!ARTC	2.0
>!AACPIButtons	6.1
>!AHPET	1.8
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	311
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
>!AHIDKeyboard	224
>!AMultitouchDriver	4440.3
>!AInputDeviceSupport	4400.35
>!AHS!BDriver	4050.1
>IO!BHIDDriver	8.0.5d7
@kext.triggers	1.0
>!AGraphicsControl	6.3.3
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
|IOSerial!F	11
|IOAVB!F	940.4
|IOEthernetAVB!C	1.1.0
|IONDRVSupport	585.1
>!ASMBus!C	1.0.18d1
|IOAccelerator!F2	442.9
>X86PlatformPlugin	1.0.0
>!ASMBusPCI	1.0.14d1
>!AHDA!C	283.15
|IOHDA!F	283.15
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
|Broadcom!BHost!CUSBTransport	8.0.5d7
|IO!BHost!CUSBTransport	8.0.5d7
|IO!BHost!CTransport	8.0.5d7
>!AThunderboltEDMSink	5.0.3
>IOPlatformPlugin!F	6.0.0d8
@!AGPUWrangler	6.3.3
@!AGraphicsDeviceControl	6.3.3
|IOGraphics!F	585.1
|IOSlowAdaptiveClocking!F	1.0.0
@plugin.IOgPTPPlugin	985.2
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!AThunderboltDPOutAdapter	8.1.4
>!AThunderboltDPInAdapter	8.1.4
>!AThunderboltDPAdapter!F	8.1.4
>!AThunderboltPCIDownAdapter	4.1.1
>!ABSDKextStarter	3
|IOSurface	290.8.1
@filesystems.hfs.encodings.kext	1
>!AXsanScheme	3
|IOAHCIBlock!S	332
|IO80211!F	1200.12.2b1
|IOSkywalk!F	1
>corecapture	1.0.4
>mDNSOffloadUserClient	1.0.1b8
|IOAHCI!F	294.100.1
>!A!ILpssGspi	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AThunderboltNHI	7.2.8
|IOThunderbolt!F	9.3.2
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$!AImage4	3.0.0
|IOTimeSync!F	985.2
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.5d7
|IOReport!F	47
|IO!BPacketLogger	8.0.5d7
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.120.2
|IOUSBMass!SDriver	184.121.1
|IOSCSIBlockCommandsDevice	436.121.1
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.121.1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	11.1
@kec.Libm	1

======================================

Cheers.

**Comment by evillt** [comment]
Thanks, 0.7.0 does not fix any issues. I still debugging and will find a good way to handle it.

**Comment by evillt** [comment]
Fixed this in https://github.com/evillt/macmineable-release/releases/tag/v0.7.1

> yeah, appreciate your efforts. It kinda freezes, I can drag the app, however, the interface is white blank, no display of hash rate or total coin collected. here is another error message:

**Comment by evillt** [comment]
🤔 I'm not sure, maybe not macMineable.

> Good Day Anthony,
> 
> The same computer restarted a couple of time in the last 24 hour with the following error report. not sure if it's related. was running version .6.0. gonna download .7.0 and give it a try.
> 
> ============================================
> 
> panic(cpu 2 caller 0xffffff801e154b46): "vm_pageout: no victim"@/System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.121.3/osfmk/vm/vm_pageout.c:3137
> Backtrace (CPU 2), Frame : Return Address
> 0xffffffb08a88bbb0 : 0xffffff801e08e0dd
> 0xffffffb08a88bc00 : 0xffffff801e1d4f33
> 0xffffffb08a88bc40 : 0xffffff801e1c552a
> 0xffffffb08a88bc90 : 0xffffff801e032a2f
> 0xffffffb08a88bcb0 : 0xffffff801e08d8fd
> 0xffffffb08a88bdd0 : 0xffffff801e08dbf3
> 0xffffffb08a88be40 : 0xffffff801e89d81a
> 0xffffffb08a88beb0 : 0xffffff801e154b46
> 0xffffffb08a88bf70 : 0xffffff801e15524b
> 0xffffffb08a88bfa0 : 0xffffff801e03213e
> 
> Process name corresponding to current thread: kernel_task
> 
> Mac OS version:
> 20F71

**Comment by evillt** [comment]
Duplicated #4
