### ISSUE TITLE
Keep Mining even with App close and stoped 

### ISSUE THREAD

**Issue by LordYoito** [evillt/macmineable-release#9]
**Describe the bug**
I can stop or close the application gut the fan speed of the unit dose no ego down in speed and it still reflects in the unmineable website portal that it still working 

<img width="1167" alt="Screen Shot 2021-08-02 at 9 29 55 AM" src="https://user-images.githubusercontent.com/88329266/127869819-a0105080-5f04-4b8e-b171-8792060e13e9.png">
 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mojave 10.14.6
 - Model Mac (Retina 5K, 27-inch, Late 2014)

**Additional context**

**Comment by evillt** [comment]
Actually is stopped. It's just the unMineable delay problem.

**Comment by evillt** [comment]
closing this. I never faced this issue before.

Feel free to re-open this issue if you have the same problem.

**Comment by LordYoito** [comment]
It was stoped for more that an 1 hr and the fans of the iMac where full blast... sorry didn't see this in time

**Comment by evillt** [comment]
> It was stoped for more that an 1 hr and the fans of the iMac where full blast... sorry didn't see this in time

I wrote down a wiki for the edge cases. In your case is here https://github.com/evillt/macmineable-release/issues/10#issuecomment-893179198

Sorry for the issue, but I never faced this problem and I don't know how to debug it correctly.
